services:
  - type: web
    name: discord-todo-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
    healthCheckPath: /
    autoDeploy: true 